/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class ContactAssociation (
  /* The contact to be associated with the customer. Use the ContactIndex element to point to a new contact in the submission.  Use the ContactUid to point to an existing contact on Cerillion. NewContact-1 or 504  */
  contactIndex: Option[String],
  contactUid: Option[Int],
  /* The type of association. E.g. BILLCONT = Global Billing customer Only 1 association of each type is permitted.  */
  associationType: String,
  isPrimary: Boolean
) extends ApiModel


